/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.himinou.tp3v2;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author minou
 */
public class fnGestionnaire extends javax.swing.JFrame {

    /**
     * Creates new form fnGestionnaire
     */
    public fnGestionnaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_lib = new javax.swing.JLabel();
        tf_lib = new javax.swing.JTextField();
        lbl_cat = new javax.swing.JLabel();
        cbb_cat = new javax.swing.JComboBox<>();
        lbl_cat2 = new javax.swing.JLabel();
        lbl_cat2.setVisible(false);
        cbb_cat2 = new javax.swing.JComboBox<>();
        cbb_cat2.setVisible(false);
        lbl_prix = new javax.swing.JLabel();
        tf_prix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_qt = new javax.swing.JLabel();
        tf_qt = new javax.swing.JTextField();
        btn_sup = new javax.swing.JButton();
        btn_mdf = new javax.swing.JButton();
        btn_ajt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menu_fichier = new javax.swing.JMenu();
        fichier_item1 = new javax.swing.JMenuItem();
        fichier_Item2 = new javax.swing.JMenuItem();
        menu_apropos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionnaire de Produits");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produits"));

        lbl_lib.setText("Libellé");

        tf_lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_libActionPerformed(evt);
            }
        });

        lbl_cat.setText("Catégorie");

        cbb_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "Casque Audio", "Camera", "Disque Dur", "Souris" }));
        cbb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_catActionPerformed(evt);
            }
        });

        lbl_cat2.setText("Sous-Catégorie");

        cbb_cat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_cat2ActionPerformed(evt);
            }
        });

        lbl_prix.setText("Prix");

        lbl_qt.setText("Quantité");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_cat)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cat2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbb_cat2, 0, 123, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(tf_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_qt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addComponent(tf_qt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lib)
                    .addComponent(tf_lib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cat)
                    .addComponent(cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cat2)
                    .addComponent(cbb_cat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qt)
                    .addComponent(tf_qt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prix))
                .addGap(67, 67, 67))
        );

        btn_sup.setText("Supprimer");
        btn_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supMouseExited(evt);
            }
        });
        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });

        btn_mdf.setText("Modifier");
        btn_mdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mdfActionPerformed(evt);
            }
        });

        btn_ajt.setText("Ajouter");
        btn_ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajtActionPerformed(evt);
            }
        });

        jButton1.setText("son1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("son2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_fichier.setText("Fichier");

        fichier_item1.setText("Exporter Excel");
        menu_fichier.add(fichier_item1);

        fichier_Item2.setText("Quitter");
        fichier_Item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichier_Item2ActionPerformed(evt);
            }
        });
        menu_fichier.add(fichier_Item2);

        menubar.add(menu_fichier);

        menu_apropos.setText("A propos");

        jMenuItem1.setText("Aide");
        menu_apropos.add(jMenuItem1);

        jMenuItem2.setText("Version");
        menu_apropos.add(jMenuItem2);

        menubar.add(menu_apropos);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mdf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ajt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_sup)
                        .addComponent(btn_mdf)
                        .addComponent(btn_ajt))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_libActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_libActionPerformed

    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supActionPerformed
        // TODO add your handling code here:
        tf_lib.setText(" ");
        tf_prix.setText(" ");
        cbb_cat.setSelectedIndex(0);
        //lbl_cat2.setVisible(false);
        //cbb_cat2.setVisible(false);
    }//GEN-LAST:event_btn_supActionPerformed

    private void cbb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_catActionPerformed
        // TODO add your handling code here:
        if(cbb_cat.getSelectedIndex() ==1){
            cbb_cat2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fillaire","Sans-File","Noise Reducer"  }));
            lbl_cat2.setVisible(true);
            cbb_cat2.setVisible(true);
        }else{
            if(cbb_cat.getSelectedIndex() ==2){
            cbb_cat2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reflexe","Analogique","Numérique"  }));
            lbl_cat2.setVisible(true);
            cbb_cat2.setVisible(true);
            }else{
                cbb_cat2.setVisible(false);
                lbl_cat2.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_cbb_catActionPerformed

    private void cbb_cat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_cat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_cat2ActionPerformed

    private void fichier_Item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichier_Item2ActionPerformed
        // TODO add your handling code here:
        int rp = JOptionPane.showConfirmDialog(getContentPane(),"Voullez-vous vraiment nous quitter?", "Attention!", JOptionPane.YES_NO_OPTION);
					if (rp == JOptionPane.YES_OPTION) {
                                                System.exit(0);
					}
    }//GEN-LAST:event_fichier_Item2ActionPerformed

    private void btn_mdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mdfActionPerformed
        // TODO add your handling code here:
        if(!tf_lib.getText().isEmpty() || !tf_prix.getText().isEmpty()){
            JOptionPane.showInternalMessageDialog(getContentPane(), "Vous pouvez modifier directement sur les champs textes", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_mdfActionPerformed

    private void btn_supMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseEntered
        // TODO add your handling code here:
        Border etchedLine = BorderFactory. createEtchedBorder(Color.lightGray,
                Color.yellow);
            btn_sup.setBorder(etchedLine);
    }//GEN-LAST:event_btn_supMouseEntered

    private void btn_supMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supMouseExited
        // TODO add your handling code here:
        btn_sup.setBorder(btn_ajt.getBorder());
    }//GEN-LAST:event_btn_supMouseExited

    private void btn_ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajtActionPerformed
        // TODO add your handling code here:
        Float a= new Float(0);
        if(!tf_lib.getText().isEmpty() && !tf_prix.getText().isEmpty()){
             if(!tf_prix.getText().matches("[0-9]*")){
                     JOptionPane.showInternalMessageDialog(getContentPane(), "Le champ prix doit contenir une valeur numerique", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
                     
                }
        }else{
                JOptionPane.showInternalMessageDialog(getContentPane(), "Vous devez renseinger tout les champs. Merci!", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }//GEN-LAST:event_btn_ajtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fnGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fnGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fnGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fnGestionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fnGestionnaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajt;
    private javax.swing.JButton btn_mdf;
    private javax.swing.JButton btn_sup;
    private javax.swing.JComboBox<String> cbb_cat;
    private javax.swing.JComboBox<String> cbb_cat2;
    private javax.swing.JMenuItem fichier_Item2;
    private javax.swing.JMenuItem fichier_item1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_cat;
    private javax.swing.JLabel lbl_cat2;
    private javax.swing.JLabel lbl_lib;
    private javax.swing.JLabel lbl_prix;
    private javax.swing.JLabel lbl_qt;
    private javax.swing.JMenu menu_apropos;
    private javax.swing.JMenu menu_fichier;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JTextField tf_lib;
    private javax.swing.JTextField tf_prix;
    private javax.swing.JTextField tf_qt;
    // End of variables declaration//GEN-END:variables
}
